const CONSULTATION_STATUS = {

    IN_PROGRESS: "IN_PROGRESS",

    ROUTING: "ROUTING",

    CLARIFICATION_REQUIRED:
        "CLARIFICATION_REQUIRED",

    ROUTED: "ROUTED",

    INSUFFICIENT_MATCH:
        "INSUFFICIENT_MATCH",

    HUMAN_REVIEW:
        "HUMAN_REVIEW",

    APPOINTMENT_BOOKED:
        "APPOINTMENT_BOOKED",

    COMPLETED:
        "COMPLETED"

};

module.exports = {
    CONSULTATION_STATUS
};